spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demand?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false&serverTimezone=GMT%2b8
    username: admin
    password: 1qaz!QAZ
    driverClassName: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    #dataSource Pool configuration; ip:port/busi/druid/datasource.html
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      use-global-data-source-stat: true
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      #配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filter: {stat,wall,log4j}
  application:
    name: business
  ## 为了支持周报, 前台暂时还没写好, 先暂时用thymeleaf支撑一下, 等后面VUE项目OK了, 就删除掉
  thymeleaf:
    prefix: classpath:/htmls/
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址,dev访问本机,prd配置主机ip
    host: localhost
    port: 6379
    password:
    # 连接池最大连接数（使用负值表示没有限制）
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 20
        # 连接池最大阻塞等待时间（使用负值表示没有限制（毫秒））
        max-wait: 10000
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接超时时间（毫秒）
        timeout: 1000

server:
  port: 8081

logging:
  level:
    com.west.business : debug
  config: classpath:config/logback-dev.xml
  # 日志文件夹地址
  path: ./logs

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://user:123@127.0.0.1:10001/eureka/,http://user:123@127.0.0.1:10000/eureka/
#    healthcheck: 
#      enabled: true #使用health端点来代替心跳表明服务是否可用，反应到eureka server ui上服务的UP还是DOWN
#  instance:
#    prefer-ip-address: true # 在eureka页面显示ip

