spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mplus?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
  application:
    name: provider-user

server: 
  servlet: 
    context-path: /user
  port: 8081

logging:
  level:
    com.young : debug

eureka: 
  client: 
    serviceUrl:
      defaultZone: http://user:123@127.0.0.1:10001/eureka/,http://user:123@127.0.0.1:10000/eureka/
#    healthcheck: 
#      enabled: true #使用health端点来代替心跳表明服务是否可用，反应到eureka server ui上服务的UP还是DOWN
  instance:
    prefer-ip-address: true # 在eureka页面显示ip